// src/data.js
export const jobsData = [
  {
    company: "Amazon",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
    days: "5 days ago",
    title: "Senior UI/UX Designer",
    type: "Part - Time",
    level: "Senior Level",
    salary: "$120/hr",
    location: "Mumbai, India",
  },
  {
    company: "Google",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    days: "2 days ago",
    title: "Frontend Engineer",
    type: "Full - Time",
    level: "Mid Level",
    salary: "$150/hr",
    location: "Bangalore, India",
  },
  {
    company: "Apple",
    logo: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    days: "1 day ago",
    title: "Product Designer",
    type: "Contract",
    level: "Senior Level",
    salary: "$180/hr",
    location: "California, USA",
  },
  {
    company: "Netflix",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg",
    days: "3 days ago",
    title: "Backend Developer",
    type: "Full - Time",
    level: "Mid Level",
    salary: "$140/hr",
    location: "Remote",
  },
  {
    company: "Meta",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/05/Meta_Platforms_Logo.svg",
    days: "6 days ago",
    title: "AR/VR Engineer",
    type: "Full - Time",
    level: "Senior Level",
    salary: "$200/hr",
    location: "New York, USA",
  },
  {
    company: "Microsoft",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    days: "4 days ago",
    title: "Cloud Solutions Architect",
    type: "Full - Time",
    level: "Senior Level",
    salary: "$170/hr",
    location: "Hyderabad, India",
  },
  {
    company: "Tesla",
    logo: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Tesla_Motors.svg",
    days: "8 days ago",
    title: "Machine Learning Engineer",
    type: "Full - Time",
    level: "Mid Level",
    salary: "$160/hr",
    location: "Texas, USA",
  },
  {
    company: "NVIDIA",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Nvidia_logo.svg",
    days: "7 days ago",
    title: "AI Research Scientist",
    type: "Full - Time",
    level: "Senior Level",
    salary: "$220/hr",
    location: "California, USA",
  },
  {
    company: "Adobe",
    logo: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Adobe_logo.svg",
    days: "2 days ago",
    title: "Creative Cloud Engineer",
    type: "Part - Time",
    level: "Junior Level",
    salary: "$110/hr",
    location: "Remote",
  },
  {
    company: "IBM",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg",
    days: "9 days ago",
    title: "Data Analyst",
    type: "Full - Time",
    level: "Entry Level",
    salary: "$95/hr",
    location: "Pune, India",
  }
];
