// src/data.js
export const jobsData = [
  {
    company: "Amazon",
    logo: "https://imgs.search.brave.com/pw-iFxvWWPNXLVEcHxz-QiyqdZatr91Zby9NXatuKQ0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly8xMDAw/bG9nb3MubmV0L3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDE2LzEw/L0FtYXpvbi1sb2dv/LW1lYW5pbmctNTAw/eDI1MC5qcGc",
    days: "5 days ago",
    title: "Senior UI/UX Designer",
    type: "Part - Time",
    level: "Senior Level",
    salary: "$120/hr",
    location: "Mumbai, India",
  },
  {
    company: "Google",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiEndPkpxU-FDOQK0acJ6iuFECTI914xOelQ&s",
    days: "2 days ago",
    title: "Frontend Engineer",
    type: "Full - Time",
    level: "Mid Level",
    salary: "$150/hr",
    location: "Bangalore, India",
  },
  {
    company: "Apple",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5rIxFRNX2QZlnQidGjE75yAg9jR4Jhy3Jgw&s",
    days: "1 day ago",
    title: "Product Designer",
    type: "Contract",
    level: "Senior Level",
    salary: "$180/hr",
    location: "California, USA",
  },
  {
    company: "Netflix",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK-b-GRJP49S_nvl8UDCQ2DDusVBUmQcN1Ug&s",
    days: "3 days ago",
    title: "Backend Developer",
    type: "Full - Time",
    level: "Mid Level",
    salary: "$140/hr",
    location: "Remote",
  },
  {
    company: "Meta",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzZPJAE0dqPukUcuiRdQe0U0oNM6IM7B_ZSA&s",
    days: "6 days ago",
    title: "AR/VR Engineer",
    type: "Full - Time",
    level: "Senior Level",
    salary: "$200/hr",
    location: "New York, USA",
  },
  {
    company: "Microsoft",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQymlLk2n_Q7xiznxOX7LfDQYZPCAt8g-GCEw&s",
    days: "4 days ago",
    title: "Cloud Solutions Architect",
    type: "Full - Time",
    level: "Senior Level",
    salary: "$170/hr",
    location: "Hyderabad, India",
  },
  {
    company: "Tesla",
    logo: "https://pngimg.com/d/tesla_logo_PNG19.png",
    days: "8 days ago",
    title: "Machine Learning Engineer",
    type: "Full - Time",
    level: "Mid Level",
    salary: "$160/hr",
    location: "Texas, USA",
  },
  {
    company: "NVIDIA",
    logo: "https://www.citypng.com/public/uploads/preview/hd-nvidia-eye-logo-icon-png-701751694965655t2lbe7yugk.png?v=2025081722",
    days: "7 days ago",
    title: "AI Research Scientist",
    type: "Full - Time",
    level: "Senior Level",
    salary: "$220/hr",
    location: "California, USA",
  },
  {
    company: "Adobe",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTonVNsfzvIrKxFgcvMhXtw3Mh4NX9re2B7Vg&s",
    days: "2 days ago",
    title: "Creative Cloud Engineer",
    type: "Part - Time",
    level: "Junior Level",
    salary: "$110/hr",
    location: "Remote",
  },
  {
    company: "IBM",
    logo: "https://static.vecteezy.com/system/resources/previews/021/514/722/non_2x/ibm-brand-symbol-software-computer-logo-design-illustration-free-vector.jpg",
    days: "9 days ago",
    title: "Data Analyst",
    type: "Full - Time",
    level: "Entry Level",
    salary: "$95/hr",
    location: "Pune, India",
  }
];
